version: '3'

vars:
  NETATMO_CMD: uv run python cli.py

tasks:
  list-rooms:
    desc: List all rooms with thermostats
    cmds:
      - "{{.NETATMO_CMD}} list-rooms"
    aliases: [ls, rooms]

  set-temp:
    desc: Set temperature for a room by name (e.g., task set-temp ROOM="Bureau" TEMP=20.5)
    prompt: Set {{.ROOM}} to {{.TEMP}}°C?
    cmds:
      - "{{.NETATMO_CMD}} set-truetemperature --room-name '{{.ROOM}}' --temperature {{.TEMP}}"
    requires:
      vars: [ROOM, TEMP]

  bureau:
    desc: Set temperature for Bureau
    cmds:
      - task: set-temp
        vars:
          ROOM: Bureau
          TEMP: "{{.TEMP}}"

  salle-a-manger:
    desc: Set temperature for Salle à manger
    cmds:
      - task: set-temp
        vars:
          ROOM: Salle à manger
          TEMP: "{{.TEMP}}"

  chambre-liam:
    desc: Set temperature for Chambre Liam
    cmds:
      - task: set-temp
        vars:
          ROOM: Chambre Liam
          TEMP: "{{.TEMP}}"

  couloir:
    desc: Set temperature for Couloir
    cmds:
      - task: set-temp
        vars:
          ROOM: Couloir
          TEMP: "{{.TEMP}}"

  list:
    desc: List all available tasks
    cmds:
      - task --list-all
