version: '3'

tasks:
  show:
    desc: "Display the full changelog"
    aliases: ["view", "cat"]
    cmds:
      - cat CHANGELOG.md

  preview:
    desc: "Preview what would be added to changelog"
    aliases: ["dry-run"]
    cmds:
      - echo "📝 Previewing changelog changes..."
      - uv run cz changelog --dry-run --incremental

  latest:
    desc: "Show only the latest release section"
    cmds:
      - |
        TAG="{{.GET_LATEST_TAG}}"
        VERSION=$(echo "$TAG" | sed 's/^v//')
        if [ -z "$VERSION" ]; then
          echo "No releases yet"
          exit 0
        fi

        echo "📝 Changelog for version $VERSION:"
        echo ""
        awk '/^## '"$VERSION"'/,/^## [0-9]/' CHANGELOG.md | sed '$d'

  unreleased:
    desc: "Show unreleased changes section"
    cmds:
      - |
        echo "📝 Unreleased changes:"
        echo ""
        awk '/^## \[Unreleased\]/,/^## [0-9]/' CHANGELOG.md | sed '$d'

  validate:
    desc: "Validate changelog format"
    cmds:
      - |
        echo "🔍 Validating CHANGELOG.md..."

        if ! grep -q "# Changelog" CHANGELOG.md; then
          echo "❌ Missing '# Changelog' header"
          exit 1
        fi

        if ! grep -q "Keep a Changelog" CHANGELOG.md; then
          echo "⚠️  Missing 'Keep a Changelog' reference"
        fi

        if ! grep -q "Semantic Versioning" CHANGELOG.md; then
          echo "⚠️  Missing 'Semantic Versioning' reference"
        fi

        echo "✅ Changelog format looks good!"
